### ISSUE TITLE
sbb chrome で remember-me 認証エラーが発生する。

### ISSUE THREAD

**Issue by live134** [live134/webapps#10]
エラー発生手順
・chrome で remember-me 認証ログイン。
・/login にアクセスしたりする。
・ブラウザを落として、再度アクセス。
・エラー発生。

補足
・たまにエラーが発生しないことがある。
・開発者モードだと良く発生する。 / へのアクセスでもたまに発生していた。

エラー詳細
org.springframework.security.web.authentication.rememberme.CookieTheftException: Invalid remember-me token (Series/token) mismatch. Implies previous cookie theft attack.
	at org.springframework.security.web.authentication.rememberme.PersistentTokenBasedRememberMeServices.processAutoLoginCookie(PersistentTokenBasedRememberMeServices.java:102)
	at org.springframework.security.web.authentication.rememberme.AbstractRememberMeServices.autoLogin(AbstractRememberMeServices.java:115)

**Comment by live134** [comment]
live134/sbbに移動。
